### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by codefromthecrypt** [DealerDotCom/zipkin-elasticbeanstalk#1]
There are a few bootstrapping concerns. Got pretty far, but need to know how to setup the environment.

I added AmazonS3FullAccess and AWSElasticBeanstalkFullAccess to my IAM user..

created the bucket for my account..

```
aws s3 mb elasticbeanstalk-ap-southeast-1-123456789
```

created the application...

```
aws elasticbeanstalk create-application --application-name zipkin
```

but I don't know the parameters for the environment

```
$ aws elasticbeanstalk create-environment --application-name zipkin --environment-name zipkin

An error occurred (MissingParameter) when calling the CreateEnvironment operation: You must specify either Configuration Template name or Solution Stack name.
```

**Comment by devinsba** [comment]
Ok, I'll add these into the readme

**Comment by codefromthecrypt** [comment]
thanks!
